"""add opt_out table

Revision ID: d17bd3601c0c
Revises: 1751740333
Create Date: 2025-11-30 14:49:48.639915

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d17bd3601c0c"
down_revision: Union[str, None] = "1751740333"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "opt_out",
        sa.Column("jid", sa.String(length=255), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("opt_out")
    # ### end Alembic commands ###
